### ISSUE TITLE
Feature request: Search bar

### ISSUE THREAD

**Issue by Free-BSG** [osu-cass/whats-fresh-api#27]
So I noticed in the data entry pages, that once we have entered a lot of products or vendors, we will have pages of data items. My issue stems from the idea that if a vendor/product/preparation/image/video needs to be deleted/updated, how do I find that specific data item. If there are 200 pages of vendors, I don't wan't to have to scroll through all of the vendors to find the one I want to delete/update. I would like to have a search bar so that I could find a specific vendor/product/preparation/image/video. Note that the search bar would only search for vendors if you are currently looking at the vendors list, products if you are looking at the products list, and so on.

**Comment by tschuy** [comment]
Fixed by #57
