### ISSUE TITLE
Feature request: inline sub-forms

### ISSUE THREAD

**Issue by Kennric** [osu-cass/whats-fresh-api#47]
When adding products, it would be nice to be able to add preparations within the product form, rather than have to have them pre-added in a separate form. Any object with sub-items that need to be added first should be restructured so that the sub-items can be added inline with the object.

**Comment by iCHAIT** [comment]
Does this mean that the preparation form should be scrapped entirely or the aim is to just provide an extra alternative to the user to be able to enter the preparations from product form also??
Also could you please explain `Any object with sub-items that need to be added first should be restructured so that the sub-items can be added inline with the object.`?

**Comment by Kennric** [comment]
This is harder to explain in text, I will look for a form in the wild that displays the functionality I am talking about.
Meanwhile, consider this:
You are adding a product. This product requires you to specify all the 'preparations' the product comes in, like frozen, fresh, smoked, etc. These preparations are separate objects in the database, and are added via a separate form.

As you select the preparations from the drop-down selector, you see that one preparation you need, 'cooked', is missing from the list. With the current form, you have only two options, you can save the Product without the 'cooked' preparation, go add the preparation in its own form, and then edit the product and add 'cooked'. Or, you can cancel, go create 'cooked', and start over.

Here is the feature we want: instead of those two options, we have an 'add' button next to the list of preparations - if the preparation you need is not on the list, you click 'add' and a new form pops up - either inline (using javascript), or in a pop-up window. This new form lets you add the new preparation, which you can then add to the product and finally save the product.

This will be useful for images, videos, preparations, maybe even adding products as you add a vendor.

Is that more clear?

**Comment by iCHAIT** [comment]
Yes.
Thanks a lot.

**Comment by iCHAIT** [comment]
@Kennric I was wondering that we could implement the same thing in the Vendors form as well i.e when we are adding Vendors, an inline sub-form can be provided so that the products can be added within the Vendor form as well.
What do you think?

**Comment by iCHAIT** [comment]
I just realized that you have already answered my above question in your comment.

**Comment by iCHAIT** [comment]
This can be closed?

**Comment by tschuy** [comment]
Indeed :)
