### ISSUE TITLE
Feature request: Map input for locations

### ISSUE THREAD

**Issue by Kennric** [osu-cass/whats-fresh-api#51]
When entering a location/address, include a graphical map input. The user can choose a point on the map, but if they only enter an address, that will be translated dynamically to coordinates and displayed on the map (so the user can visually double-check that the location is correct).

The database stores a coordinate location for Vendors - if a point is selected, simply use those coordinates, no matter what is entered into the address fields.

**Comment by Kennric** [comment]
Here is an image similar to what I have in mind: https://thomas.rabaix.net/uploads/multifield-widget/preview.png - one can enter an address in the address field, and this address will be marker on the map, and the coordinates will be added to the coordinate fields.

OR: one can select a location by clicking on the map, and this will populate the coordinate fields. When the form is submitted, the coordinates and written address (if provided), will be submitted.

**Comment by iCHAIT** [comment]
This can be closed now, I think.

**Comment by tschuy** [comment]
It can indeed :yum:
