### ISSUE TITLE
Feature request: web instance of mobile app

### ISSUE THREAD

**Issue by Kennric** [osu-cass/whats-fresh-api#54]
It would be nice to access the mobile app functionality (minus gps location) via the web. This could be accomplished by including a web-build of the mobile app (Sencha can easily generate these), or by implementing the same search tools in a new web interface. We could use this web inteface to the database as the default front page of the app, for people who are not logged in, or provide a link to it.

**Comment by jhcarr** [comment]
I only just saw this feature request (almost exactly a year later. Sorry everyone.). Would it make more sense to do a "give you a fish" solution or a "teach you to fish" solution? Both are pretty straightforward.

I think the last time we tried to send you a Sencha web build it wouldn't run outside the Sencha environment - as though it still needed the Sencha Touch API source folder to function.
