### ISSUE TITLE
Use SVG icons in place of PNG icons

### ISSUE THREAD

**Issue by tschuy** [osu-cass/whats-fresh-api#68]
With proper fallbacks, of course.

The current trashcan icon is, I believe, the only raster image on the entire site. That makes me sad :(

There are tools like icomoon, and things like SVG's `<symbol>` and `<use>` tags, that will allow us to replace it easily.

**Comment by tschuy** [comment]
I kinda like this delete icon: https://thenounproject.com/search/?q=delete&i=50864

**Comment by iCHAIT** [comment]
Looks nice :+1:

**Comment by tschuy** [comment]
I had some extra time and felt like playing around with the Google Material Font library, so I've implemented it on my ``more_sanity`` branch where I've been putting occasional minor fixes. Here's how it looks:

![new looks](http://i.imgur.com/J8FcqPl.png)

**Comment by iCHAIT** [comment]
That looks super cool, we should definitely have this :+1:
