### ISSUE TITLE
Vendor information form does not allow saving of phone numbers

### ISSUE THREAD

**Issue by jhcarr** [osu-cass/whats-fresh-api#79]
Repro steps:
1. Navigate to http://whats-fresh-api.osuosl.org/entry/vendors/4
2. Enter a phone number, such as (123) 456-7890, into the field labeled "Phone:"
3. Click the Save button at the bottom of the page

Expected result: Page is updated, preserving existing data for vendors/4, but with the value from step 2 visible in the "Phone:" field

Actual result: Page is refreshed, preserving existing data for vendors/4, but no new value appears in the "Phone:" field.

**Comment by Kennric** [comment]
This appears to be a format issue. The phone number field is set to use the international E.164 phone number format, and can't handle our usual US style number format. 
Phone numbers should work if entered with no spaces, dashes, or parentheses and prefixed by '+1'

should work:
 +15417371111

doesn't work:

(541) 737-1111

I will experiment to see if I can get it to accept more casually formatted numbers in an intelligent way (hopefully with just a settings change), but meanwhile, entering with the E.164 format should work on the existing code.

**Comment by tschuy** [comment]
This should at the very least be documented in/by the entry field. My bad, sorry :(
